server:
  port: 9000
spring:
  application:
    name: api-gateway
  threads:
    virtual:
      enabled: true
  cloud:
    gateway:
      routes:
        - id: core
          uri: 'http://localhost:9010'
          predicates:
          - Path=/core-services/**
          filters:
          - StripPrefix=1
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: health