
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health
spring:
  threads:
    virtual:
      enabled: true