server:
  port: 9011
spring:
  application:
    name: api-gateway
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce?connectTimeoutMS=300000&minPoolSize=0&maxPoolSize=1000&maxIdleTimeMS=900000
      username: tdd_platform
      password: Tdd@plf2023
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: health
